spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application: 
    name: microservicecloud-config-dzq-dev
---
spring:
  profiles: test
  application: 
    name: microservicecloud-config-dzq-test
#请保存为UTF-8格式